In [27]:
import pandas as pd

df = pd.read_excel('/Users/selinzobu/Desktop/data-engineer-challenge-crawler/data_loader/example-data.xlsx')

In [28]:
df.head()

,NO,ARRIVAL DATE,HS CODE,HS CODE DESCRIPTION,IMPORTER ADDRESS,IMPORTER COUNTRY,TEL,E-MAIL,WEB,EXPORTER ADDRESS,...,GROSS WEIGHT,GROSS WEIGHT UNIT,QUANTITY,QUANTITY UNIT,PRODUCT DETAILS,NUMBER OF PACKAGES,PACKAGES UNIT,PLACE OF DELIVERY,MANUFACTORING COMPANY,VOLUME
0,1,2024-01-31,20041021,"Potatoes, prepared or preserved otherwise than...",.,Botswana,.,.,https://www.woolworths.co.za,NaN,...,63.81,Kilogram,96.0,KGM,Potatoes Chips or French fries Prepared by bla...,96,EACH,NaN,NaN,0
1,2,2024-01-31,20041021,"Potatoes, prepared or preserved otherwise than...",.,Botswana,.,.,NaN,NaN,...,1000.00,Kilogram,60.0,KGM,Potatoes Chips or French fries Prepared by bla...,60,PACKAGE,NaN,NaN,0
2,3,2024-01-31,20041000,"PAPAS (PATATAS),PREPARADAS O CONSERVADAS, EXC....",.,Chile,.,.,https://www.icbfs.cl,NaN,...,268667.70,Kilogram,8400.0,KILOGRAMOS NETOS,PAPAS PREPARADAS O EN CONSERVAAVIKOTIPO DE ENV...,13,CONTENEDOR REFRIGERADO 40,NaN,NaN,0
3,4,2024-01-31,20041000,"PAPAS (PATATAS),PREPARADAS O CONSERVADAS, EXC....",Sra. Claudia Naulin,Chile,+56 25571125,gerencia@comercialcastro.cl,https://castro.red,NaN,...,25993.80,Kilogram,25200.0,KILOGRAMOS NETOS,PAPAS PREFRITASTIPO DE ENVASE :CAJAS DE CARTON...,1,CONTENEDOR REFRIGERADO 40,NaN,NaN,0
4,5,2024-01-31,20041000,"PAPAS (PATATAS),PREPARADAS O CONSERVADAS, EXC....",.,Chile,.,.,NaN,NaN,...,51296.71,Kilogram,24192.0,KILOGRAMOS NETOS,PAPAS PREFRITAS CONGELADASBOLSA2CAJA CON 6 BOL...,2,CONTENEDOR REFRIGERADO 40,NaN,NaN,0

In [29]:
df

,NO,ARRIVAL DATE,HS CODE,HS CODE DESCRIPTION,IMPORTER ADDRESS,IMPORTER COUNTRY,TEL,E-MAIL,WEB,EXPORTER ADDRESS,...,GROSS WEIGHT,GROSS WEIGHT UNIT,QUANTITY,QUANTITY UNIT,PRODUCT DETAILS,NUMBER OF PACKAGES,PACKAGES UNIT,PLACE OF DELIVERY,MANUFACTORING COMPANY,VOLUME
0,1,2024-01-31,20041021,"Potatoes, prepared or preserved otherwise than...",.,Botswana,.,.,https://www.woolworths.co.za,NaN,...,63.81,Kilogram,96.0,KGM,Potatoes Chips or French fries Prepared by bla...,96,EACH,NaN,NaN,0
1,2,2024-01-31,20041021,"Potatoes, prepared or preserved otherwise than...",.,Botswana,.,.,NaN,NaN,...,1000.00,Kilogram,60.0,KGM,Potatoes Chips or French fries Prepared by bla...,60,PACKAGE,NaN,NaN,0
2,3,2024-01-31,20041000,"PAPAS (PATATAS),PREPARADAS O CONSERVADAS, EXC....",.,Chile,.,.,https://www.icbfs.cl,NaN,...,268667.70,Kilogram,8400.0,KILOGRAMOS NETOS,PAPAS PREPARADAS O EN CONSERVAAVIKOTIPO DE ENV...,13,CONTENEDOR REFRIGERADO 40,NaN,NaN,0
3,4,2024-01-31,20041000,"PAPAS (PATATAS),PREPARADAS O CONSERVADAS, EXC....",Sra. Claudia Naulin,Chile,+56 25571125,gerencia@comercialcastro.cl,https://castro.red,NaN,...,25993.80,Kilogram,25200.0,KILOGRAMOS NETOS,PAPAS PREFRITASTIPO DE ENVASE :CAJAS DE CARTON...,1,CONTENEDOR REFRIGERADO 40,NaN,NaN,0
4,5,2024-01-31,20041000,"PAPAS (PATATAS),PREPARADAS O CONSERVADAS, EXC....",.,Chile,.,.,NaN,NaN,...,51296.71,Kilogram,24192.0,KILOGRAMOS NETOS,PAPAS PREFRITAS CONGELADASBOLSA2CAJA CON 6 BOL...,2,CONTENEDOR REFRIGERADO 40,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,94,2024-01-31,20041001,Papas (patatas).,.,Mexico,.,.,https://www.electrocomponentes.com,NaN,...,19136.00,Kilogram,2939.0,KILO,PAPAS CONGELADAS.,0,NaN,NaN,NaN,0
104,95,2024-01-31,20041099,Other,"P O BOX 11258, KLEIN WINDHOEK ERF 422, URBAN V...",Namibia,.,.,http://rutoco.ru,NaN,...,12.34,Kilogram,12.8,Kilogram,OTHER VEGETABLES PREPARED OR PRESER,1,PACKAGE,NaN,NaN,0
105,96,2024-01-31,2004100000,Potatoes,.,Nigeria,.,.,.,NaN,...,0.00,NaN,0.0,NaN,POTATOE FLOUR,0,NaN,NaN,NaN,0
106,97,2024-01-31,2004100000,PAPAS (PATATAS) PREPARADAS O CONSERVADAS (EXCE...,.,Peru,.,.,.,NaN,...,5041.00,Kilogram,4800.0,KG,"PAPAS PRECOCIDAS, POMRACO, S/M POMRACO FRITES ...",0,CRT,NaN,NaN,0
107,98,2024-01-31,2004100000,PAPAS (PATATAS) PREPARADAS O CONSERVADAS (EXCE...,PANAMERICANA SUR KM 18.5 ZONA INDUSTRIAL LA CO...,Peru,.,.,https://www.axionlog.com,NaN,...,23497.20,Kilogram,2196.0,CRT,"PAPAS FRITAS, AVIKO, S/M AVIKO H CRINKLE CUT F...",2196,CRT,NaN,NaN,0

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   NO                     108 non-null    int64
 1   ARRIVAL DATE           108 non-null    datetime64[ns]
 2   HS CODE                108 non-null    int64
 3   HS CODE DESCRIPTION    108 non-null    object
 4   IMPORTER ADDRESS       108 non-null    object
 5   IMPORTER COUNTRY       108 non-null    object
 6   TEL                    108 non-null    object
 7   E-MAIL                 108 non-null    object
 8   WEB                    91 non-null     object
 9   EXPORTER ADDRESS       27 non-null     object
 10  COUNTRY OF ORIGIN      106 non-null    object
 11  IMPORT VALUE           108 non-null    float64
 12  CURRENCY               105 non-null    object
 13  NET WEIGHT             108 non-null    float64
 14  NET WEIGHT UNIT        36 non-null     object
 15  GROSS WEIGHT           108 non-null    float64
 16  GROSS WEIGHT UNIT      91 non-null     object
 17  QUANTITY               108 non-null    float64
 18  QUANTITY UNIT          94 non-null     object
 19  PRODUCT DETAILS        105 non-null    object
 20  NUMBER OF PACKAGES     108 non-null    int64
 21  PACKAGES UNIT          46 non-null     object
 22  PLACE OF DELIVERY      3 non-null      object
 23  MANUFACTORING COMPANY  0 non-null      float64
 24  VOLUME                 108 non-null    int64
dtypes: datetime64[ns](1), float64(5), int64(4), object(15)
memory usage: 21.2+ KB

In [31]:
df.describe()

,NO,HS CODE,IMPORT VALUE,NET WEIGHT,GROSS WEIGHT,QUANTITY,NUMBER OF PACKAGES,MANUFACTORING COMPANY,VOLUME
count,108.000000,1.080000e+02,1.080000e+02,108.000000,108.000000,108.000000,108.000000,0.0,108.0
mean,53.574074,1.202277e+09,4.978001e+05,5564.661852,49265.809722,9539.602593,154.574074,NaN,0.0
std,29.964840,3.802218e+09,3.507281e+06,15451.812912,86111.207835,17206.850632,639.933922,NaN,0.0
min,1.000000,2.004100e+05,0.000000e+00,0.000000,0.000000,0.000000,0.000000,NaN,0.0
25%,27.750000,2.004100e+07,1.807740e+03,0.000000,687.500000,136.500000,0.000000,NaN,0.0
50%,54.500000,2.004100e+07,7.045140e+03,0.000000,18839.420000,2613.685000,0.000000,NaN,0.0
75%,81.250000,2.004100e+09,2.957201e+04,662.500000,25208.410000,17248.335000,6.000000,NaN,0.0
max,98.000000,2.004103e+10,2.591183e+07,113342.000000,268667.700000,120000.000000,4420.000000,NaN,0.0

In [32]:
df.columns

Index(['NO', 'ARRIVAL DATE', 'HS CODE', 'HS CODE DESCRIPTION',
       'IMPORTER ADDRESS', 'IMPORTER COUNTRY', 'TEL', 'E-MAIL', 'WEB',
       'EXPORTER ADDRESS', 'COUNTRY OF ORIGIN', 'IMPORT VALUE', 'CURRENCY',
       'NET WEIGHT', 'NET WEIGHT UNIT', 'GROSS WEIGHT', 'GROSS WEIGHT UNIT',
       'QUANTITY', 'QUANTITY UNIT', 'PRODUCT DETAILS', 'NUMBER OF PACKAGES',
       'PACKAGES UNIT', 'PLACE OF DELIVERY', 'MANUFACTORING COMPANY',
       'VOLUME'],
      dtype='object')

In [33]:
initial_count = len(df)
df1 = df.drop_duplicates()
print(f"Removed {initial_count - len(df1)} duplicate rows.") 
print(initial_count, len(df1))
#10 duplicate rows removed.

Removed 10 duplicate rows.
108 98

In [37]:
# Step 3: Drop empty columns (fully NaN)
"""initial_count2 = len(df1)
df2 = df1.dropna(axis=1, how='all')
print(f"Dropped {initial_count2 - len(df1.columns)} empty columns.")
print(initial_count2, len(df2))"""

'initial_count2 = len(df1)\ndf2 = df1.dropna(axis=1, how=\'all\')\nprint(f"Dropped {initial_count2 - len(df1.columns)} empty columns.")\nprint(initial_count2, len(df2))'

In [40]:
# Detect all NaN, None, or empty cells
nan_or_empty = df1.isnull() | df1.applymap(lambda x: str(x).strip() == '')
print("Cells that are NaN, None, or empty:")
print(nan_or_empty)

Cells that are NaN, None, or empty:
       NO  ARRIVAL DATE  HS CODE  HS CODE DESCRIPTION  IMPORTER ADDRESS  \
0   False         False    False                False             False
1   False         False    False                False             False
2   False         False    False                False             False
3   False         False    False                False             False
4   False         False    False                False             False
..    ...           ...      ...                  ...               ...
93  False         False    False                False             False
94  False         False    False                False             False
95  False         False    False                False             False
96  False         False    False                False             False
97  False         False    False                False             False

    IMPORTER COUNTRY    TEL  E-MAIL    WEB  EXPORTER ADDRESS  ...  \
0              False  False   False  False              True  ...
1              False  False   False   True              True  ...
2              False  False   False  False              True  ...
3              False  False   False  False              True  ...
4              False  False   False   True              True  ...
..               ...    ...     ...    ...               ...  ...
93             False  False   False  False              True  ...
94             False  False   False  False              True  ...
95             False  False   False  False              True  ...
96             False  False   False  False              True  ...
97             False  False   False  False              True  ...

    NET WEIGHT UNIT  GROSS WEIGHT  GROSS WEIGHT UNIT  QUANTITY  QUANTITY UNIT  \
0             False         False              False     False          False
1             False         False              False     False          False
2              True         False              False     False          False
3              True         False              False     False          False
4              True         False              False     False          False
..              ...           ...                ...       ...            ...
93             True         False              False     False          False
94            False         False              False     False          False
95            False         False               True     False           True
96            False         False              False     False          False
97            False         False              False     False          False

    PRODUCT DETAILS  NUMBER OF PACKAGES  PACKAGES UNIT  PLACE OF DELIVERY  \
0             False               False          False               True
1             False               False          False               True
2             False               False          False               True
3             False               False          False               True
4             False               False          False               True
..              ...                 ...            ...                ...
93            False               False           True               True
94            False               False          False               True
95            False               False           True               True
96            False               False          False               True
97            False               False          False               True

    VOLUME
0    False
1    False
2    False
3    False
4    False
..     ...
93   False
94   False
95   False
96   False
97   False

[98 rows x 24 columns]

In [43]:
columns_with_issues = nan_or_empty.any(axis=0)
print("\nColumns with NaN, None, or empty cells:")
print(columns_with_issues[columns_with_issues].index)

Columns with NaN, None, or empty cells:
Index(['WEB', 'EXPORTER ADDRESS', 'COUNTRY OF ORIGIN', 'CURRENCY',
       'NET WEIGHT UNIT', 'GROSS WEIGHT UNIT', 'QUANTITY UNIT',
       'PRODUCT DETAILS', 'PACKAGES UNIT', 'PLACE OF DELIVERY'],
      dtype='object')

In [47]:
df['EXPORTER ADDRESS'] = df['EXPORTER ADDRESS'].astype(str)
type(df['EXPORTER ADDRESS'][0])

str

In [52]:
print(df['EXPORTER ADDRESS'])
print(type(df['EXPORTER ADDRESS'][0]))

0      nan
1      nan
2      nan
3      nan
4      nan
      ...
103    nan
104    nan
105    nan
106    nan
107    nan
Name: EXPORTER ADDRESS, Length: 108, dtype: object
<class 'str'>

In [63]:
print(df['ARRIVAL DATE'][10])
print(type(df['ARRIVAL DATE'][0]))

2024-01-31 00:00:00
<class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [66]:
type(df['IMPORT VALUE'][0])

numpy.float64